name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LLVM and system dependencies
      run: |
        sudo apt update
        sudo apt install -y zlib1g-dev libcurl4-openssl-dev libedit-dev libzstd-dev llvm-19 llvm-19-dev

    - name: Configure CMake (Linux)
      run: |
        cmake --preset github-actions-linux
        
    - name: Build (Linux)
      run: |
        cmake --build build --config Release

    - name: Package Linux binary
      run: |
        mkdir -p artifacts/linux
        cp build/Bryo artifacts/linux/bryo-linux-x64
        chmod +x artifacts/linux/bryo-linux-x64

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: bryo-linux-x64
        path: artifacts/linux/bryo-linux-x64

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download LLVM with development headers
      run: |
        # Download LLVM 18.1.8 from vovkos/llvm-package-windows which includes headers
        $llvmUrl = "https://github.com/vovkos/llvm-package-windows/releases/download/llvm-18.1.8/llvm-18.1.8-windows-amd64-msvc17-msvcrt.7z"
        $llvmPath = "${{ runner.temp }}/llvm"
        
        Write-Host "Downloading LLVM 18.1.8 with development headers..."
        Invoke-WebRequest -Uri $llvmUrl -OutFile "${{ runner.temp }}/llvm.7z"
        
        Write-Host "Extracting LLVM..."
        7z x "${{ runner.temp }}/llvm.7z" -o"$llvmPath"
        
        Write-Host "LLVM extracted to: $llvmPath"
        
        # Set environment variable for subsequent steps
        echo "LLVM_PATH=$llvmPath/llvm-18.1.8-windows-amd64-msvc17-msvcrt" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Configure CMake (Windows)
      run: |
        cmake --preset github-actions-windows -DLLVM_DIR="${env:LLVM_PATH}/lib/cmake/llvm" -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl
      env:
        VCPKG_ROOT: C:\dev\null
        
    - name: Build (Windows)
      run: |
        cmake --build build/Release --config Release

    - name: Package Windows binary
      run: |
        mkdir artifacts\windows
        copy build\Release\Bryo.exe artifacts\windows\bryo-windows-x64.exe

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: bryo-windows-x64
        path: artifacts/windows/bryo-windows-x64.exe

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: bryo-linux-x64
        path: ./

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: bryo-windows-x64
        path: ./

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bryo-linux-x64
          bryo-windows-x64.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}